#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSRGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$APPLICATION_USER" WITH PASSWORD '$APPLICATION_PASSWORD';

    GRANT USAGE ON SCHEMA "$APPLICATION_SCHEMA" TO "$APPLICATION_USER";
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA "$APPLICATION_SCHEMA" TO "$APPLICATION_USER";
    GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA "$APPLICATION_SCHEMA" TO "$APPLICATION_USER";
EOSQL
